In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('../data/data.csv')
df.head()

,air_store_id,visit_date,day_of_week,holiday_flg,air_genre_name,air_area_name,latitude,longitude,visitors
0,air_ba937bf13d40fb24,2016-01-13,Wednesday,0,Dining bar,Tōkyō-to Minato-ku Shibakōen,35.658068,139.751599,25
1,air_ba937bf13d40fb24,2016-01-14,Thursday,0,Dining bar,Tōkyō-to Minato-ku Shibakōen,35.658068,139.751599,32
2,air_ba937bf13d40fb24,2016-01-15,Friday,0,Dining bar,Tōkyō-to Minato-ku Shibakōen,35.658068,139.751599,29
3,air_ba937bf13d40fb24,2016-01-16,Saturday,0,Dining bar,Tōkyō-to Minato-ku Shibakōen,35.658068,139.751599,22
4,air_ba937bf13d40fb24,2016-01-18,Monday,0,Dining bar,Tōkyō-to Minato-ku Shibakōen,35.658068,139.751599,6

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 252108 entries, 0 to 252107
Data columns (total 9 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   air_store_id    252108 non-null  object
 1   visit_date      252108 non-null  object
 2   day_of_week     252108 non-null  object
 3   holiday_flg     252108 non-null  int64
 4   air_genre_name  252108 non-null  object
 5   air_area_name   252108 non-null  object
 6   latitude        252108 non-null  float64
 7   longitude       252108 non-null  float64
 8   visitors        252108 non-null  int64
dtypes: float64(2), int64(2), object(5)
memory usage: 17.3+ MB

In [4]:
df.rename(
    columns={
        "air_store_id": "store_id",
        "visit_date": "date",
        "day_of_week": "dow",
        "air_genre_name": "store_genre",
        "air_area_name": "area"
    },
    inplace=True
)
df.head()

,store_id,date,dow,holiday_flg,store_genre,area,latitude,longitude,visitors
0,air_ba937bf13d40fb24,2016-01-13,Wednesday,0,Dining bar,Tōkyō-to Minato-ku Shibakōen,35.658068,139.751599,25
1,air_ba937bf13d40fb24,2016-01-14,Thursday,0,Dining bar,Tōkyō-to Minato-ku Shibakōen,35.658068,139.751599,32
2,air_ba937bf13d40fb24,2016-01-15,Friday,0,Dining bar,Tōkyō-to Minato-ku Shibakōen,35.658068,139.751599,29
3,air_ba937bf13d40fb24,2016-01-16,Saturday,0,Dining bar,Tōkyō-to Minato-ku Shibakōen,35.658068,139.751599,22
4,air_ba937bf13d40fb24,2016-01-18,Monday,0,Dining bar,Tōkyō-to Minato-ku Shibakōen,35.658068,139.751599,6

In [5]:
df['date'] = pd.to_datetime(df['date'], format='%Y-%m-%d')
df.head()

,store_id,date,dow,holiday_flg,store_genre,area,latitude,longitude,visitors
0,air_ba937bf13d40fb24,2016-01-13,Wednesday,0,Dining bar,Tōkyō-to Minato-ku Shibakōen,35.658068,139.751599,25
1,air_ba937bf13d40fb24,2016-01-14,Thursday,0,Dining bar,Tōkyō-to Minato-ku Shibakōen,35.658068,139.751599,32
2,air_ba937bf13d40fb24,2016-01-15,Friday,0,Dining bar,Tōkyō-to Minato-ku Shibakōen,35.658068,139.751599,29
3,air_ba937bf13d40fb24,2016-01-16,Saturday,0,Dining bar,Tōkyō-to Minato-ku Shibakōen,35.658068,139.751599,22
4,air_ba937bf13d40fb24,2016-01-18,Monday,0,Dining bar,Tōkyō-to Minato-ku Shibakōen,35.658068,139.751599,6

In [6]:
df['month'] = df['date'].dt.month
df.head()

,store_id,date,dow,holiday_flg,store_genre,area,latitude,longitude,visitors,month
0,air_ba937bf13d40fb24,2016-01-13,Wednesday,0,Dining bar,Tōkyō-to Minato-ku Shibakōen,35.658068,139.751599,25,1
1,air_ba937bf13d40fb24,2016-01-14,Thursday,0,Dining bar,Tōkyō-to Minato-ku Shibakōen,35.658068,139.751599,32,1
2,air_ba937bf13d40fb24,2016-01-15,Friday,0,Dining bar,Tōkyō-to Minato-ku Shibakōen,35.658068,139.751599,29,1
3,air_ba937bf13d40fb24,2016-01-16,Saturday,0,Dining bar,Tōkyō-to Minato-ku Shibakōen,35.658068,139.751599,22,1
4,air_ba937bf13d40fb24,2016-01-18,Monday,0,Dining bar,Tōkyō-to Minato-ku Shibakōen,35.658068,139.751599,6,1

In [7]:
df['weekend_flg'] = df['dow'].isin(['Saturday', 'Sunday']).astype(int)
df.head()

,store_id,date,dow,holiday_flg,store_genre,area,latitude,longitude,visitors,month,weekend_flg
0,air_ba937bf13d40fb24,2016-01-13,Wednesday,0,Dining bar,Tōkyō-to Minato-ku Shibakōen,35.658068,139.751599,25,1,0
1,air_ba937bf13d40fb24,2016-01-14,Thursday,0,Dining bar,Tōkyō-to Minato-ku Shibakōen,35.658068,139.751599,32,1,0
2,air_ba937bf13d40fb24,2016-01-15,Friday,0,Dining bar,Tōkyō-to Minato-ku Shibakōen,35.658068,139.751599,29,1,0
3,air_ba937bf13d40fb24,2016-01-16,Saturday,0,Dining bar,Tōkyō-to Minato-ku Shibakōen,35.658068,139.751599,22,1,1
4,air_ba937bf13d40fb24,2016-01-18,Monday,0,Dining bar,Tōkyō-to Minato-ku Shibakōen,35.658068,139.751599,6,1,0

In [8]:
df.sort_values(['store_id', 'date'], inplace=True)
df.head()

,store_id,date,dow,holiday_flg,store_genre,area,latitude,longitude,visitors,month,weekend_flg
87534,air_00a91d42b08b08d9,2016-07-01,Friday,0,Italian/French,Tōkyō-to Chiyoda-ku Kudanminami,35.694003,139.753595,35,7,0
87535,air_00a91d42b08b08d9,2016-07-02,Saturday,0,Italian/French,Tōkyō-to Chiyoda-ku Kudanminami,35.694003,139.753595,9,7,1
87536,air_00a91d42b08b08d9,2016-07-04,Monday,0,Italian/French,Tōkyō-to Chiyoda-ku Kudanminami,35.694003,139.753595,20,7,0
87537,air_00a91d42b08b08d9,2016-07-05,Tuesday,0,Italian/French,Tōkyō-to Chiyoda-ku Kudanminami,35.694003,139.753595,25,7,0
87538,air_00a91d42b08b08d9,2016-07-06,Wednesday,0,Italian/French,Tōkyō-to Chiyoda-ku Kudanminami,35.694003,139.753595,29,7,0

In [9]:
df.reset_index(drop=True, inplace=True)
df.head()

,store_id,date,dow,holiday_flg,store_genre,area,latitude,longitude,visitors,month,weekend_flg
0,air_00a91d42b08b08d9,2016-07-01,Friday,0,Italian/French,Tōkyō-to Chiyoda-ku Kudanminami,35.694003,139.753595,35,7,0
1,air_00a91d42b08b08d9,2016-07-02,Saturday,0,Italian/French,Tōkyō-to Chiyoda-ku Kudanminami,35.694003,139.753595,9,7,1
2,air_00a91d42b08b08d9,2016-07-04,Monday,0,Italian/French,Tōkyō-to Chiyoda-ku Kudanminami,35.694003,139.753595,20,7,0
3,air_00a91d42b08b08d9,2016-07-05,Tuesday,0,Italian/French,Tōkyō-to Chiyoda-ku Kudanminami,35.694003,139.753595,25,7,0
4,air_00a91d42b08b08d9,2016-07-06,Wednesday,0,Italian/French,Tōkyō-to Chiyoda-ku Kudanminami,35.694003,139.753595,29,7,0

In [10]:
for lag_days in [1]:
    temp = df[['store_id', 'date', 'visitors']].copy()
    temp['date'] = temp['date'] + pd.Timedelta(days=lag_days)
    temp.rename(columns={'visitors': f'visitors_lag_{lag_days}'},inplace=True)
    df = pd.merge(df, temp, on=['store_id', 'date'], how='left')

df.head(7)

,store_id,date,dow,holiday_flg,store_genre,area,latitude,longitude,visitors,month,weekend_flg,visitors_lag_1
0,air_00a91d42b08b08d9,2016-07-01,Friday,0,Italian/French,Tōkyō-to Chiyoda-ku Kudanminami,35.694003,139.753595,35,7,0,NaN
1,air_00a91d42b08b08d9,2016-07-02,Saturday,0,Italian/French,Tōkyō-to Chiyoda-ku Kudanminami,35.694003,139.753595,9,7,1,35.0
2,air_00a91d42b08b08d9,2016-07-04,Monday,0,Italian/French,Tōkyō-to Chiyoda-ku Kudanminami,35.694003,139.753595,20,7,0,NaN
3,air_00a91d42b08b08d9,2016-07-05,Tuesday,0,Italian/French,Tōkyō-to Chiyoda-ku Kudanminami,35.694003,139.753595,25,7,0,20.0
4,air_00a91d42b08b08d9,2016-07-06,Wednesday,0,Italian/French,Tōkyō-to Chiyoda-ku Kudanminami,35.694003,139.753595,29,7,0,25.0
5,air_00a91d42b08b08d9,2016-07-07,Thursday,0,Italian/French,Tōkyō-to Chiyoda-ku Kudanminami,35.694003,139.753595,34,7,0,29.0
6,air_00a91d42b08b08d9,2016-07-08,Friday,0,Italian/French,Tōkyō-to Chiyoda-ku Kudanminami,35.694003,139.753595,42,7,0,34.0

In [11]:
df['visitors_last_day'] = df.groupby('store_id')['visitors'].shift(1)
df.head()

,store_id,date,dow,holiday_flg,store_genre,area,latitude,longitude,visitors,month,weekend_flg,visitors_lag_1,visitors_last_day
0,air_00a91d42b08b08d9,2016-07-01,Friday,0,Italian/French,Tōkyō-to Chiyoda-ku Kudanminami,35.694003,139.753595,35,7,0,NaN,NaN
1,air_00a91d42b08b08d9,2016-07-02,Saturday,0,Italian/French,Tōkyō-to Chiyoda-ku Kudanminami,35.694003,139.753595,9,7,1,35.0,35.0
2,air_00a91d42b08b08d9,2016-07-04,Monday,0,Italian/French,Tōkyō-to Chiyoda-ku Kudanminami,35.694003,139.753595,20,7,0,NaN,9.0
3,air_00a91d42b08b08d9,2016-07-05,Tuesday,0,Italian/French,Tōkyō-to Chiyoda-ku Kudanminami,35.694003,139.753595,25,7,0,20.0,20.0
4,air_00a91d42b08b08d9,2016-07-06,Wednesday,0,Italian/French,Tōkyō-to Chiyoda-ku Kudanminami,35.694003,139.753595,29,7,0,25.0,25.0

In [12]:
roll = (
    df.set_index('date')
      .groupby('store_id')['visitors']
      .rolling('7D', closed='left')
      .mean()
      .reset_index()
      .rename(columns={'visitors': 'visitors_mean_roll_7'})
)

df = pd.merge(df, roll, on=['store_id', 'date'], how='left')
df.head(7)

,store_id,date,dow,holiday_flg,store_genre,area,latitude,longitude,visitors,month,weekend_flg,visitors_lag_1,visitors_last_day,visitors_mean_roll_7
0,air_00a91d42b08b08d9,2016-07-01,Friday,0,Italian/French,Tōkyō-to Chiyoda-ku Kudanminami,35.694003,139.753595,35,7,0,NaN,NaN,NaN
1,air_00a91d42b08b08d9,2016-07-02,Saturday,0,Italian/French,Tōkyō-to Chiyoda-ku Kudanminami,35.694003,139.753595,9,7,1,35.0,35.0,35.000000
2,air_00a91d42b08b08d9,2016-07-04,Monday,0,Italian/French,Tōkyō-to Chiyoda-ku Kudanminami,35.694003,139.753595,20,7,0,NaN,9.0,22.000000
3,air_00a91d42b08b08d9,2016-07-05,Tuesday,0,Italian/French,Tōkyō-to Chiyoda-ku Kudanminami,35.694003,139.753595,25,7,0,20.0,20.0,21.333333
4,air_00a91d42b08b08d9,2016-07-06,Wednesday,0,Italian/French,Tōkyō-to Chiyoda-ku Kudanminami,35.694003,139.753595,29,7,0,25.0,25.0,22.250000
5,air_00a91d42b08b08d9,2016-07-07,Thursday,0,Italian/French,Tōkyō-to Chiyoda-ku Kudanminami,35.694003,139.753595,34,7,0,29.0,29.0,23.600000
6,air_00a91d42b08b08d9,2016-07-08,Friday,0,Italian/French,Tōkyō-to Chiyoda-ku Kudanminami,35.694003,139.753595,42,7,0,34.0,34.0,25.333333

In [13]:
df.isna().sum()

store_id                    0
date                        0
dow                         0
holiday_flg                 0
store_genre                 0
area                        0
latitude                    0
longitude                   0
visitors                    0
month                       0
weekend_flg                 0
visitors_lag_1          28520
visitors_last_day         829
visitors_mean_roll_7     1183
dtype: int64